FROM python:3.8-slim  

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN useradd -ms /bin/bash bryan

USER bryan

COPY ./entrypoint.sh . 

COPY ./requirements.txt . 

EXPOSE 8000

CMD ["sh", "entrypoint.sh"]


