version: "3.0"

services:
   application:
     build:
       context: .
       dockerfile: Dockerfile.start 
     volumes:
       - ./server:/app    
     ports:
       - "9000:8000"
     user: "1000:1000" 
     #command: /bin/bash -c "chown -R bryan:bryan /app"
