# Generated by Django 4.1.8 on 2023-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
