# Generated by Django 4.1.8 on 2023-11-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserver',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userserver',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
