# Generated by Django 4.1.8 on 2023-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0002_alter_userserver_lastname_alter_userserver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
