# Generated by Django 4.1.8 on 2023-11-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0005_alter_userserver_phone_alter_userserver_signsecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserver',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
